#define WINDOW_STYLE		WS_VISIBLE|WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX

#define DIGIT_WIDTH			13
#define DIGIT_HEIGHT		23
#define MINUS_OFFSET		(DIGIT_WIDTH*10)
#define FIELD_SIZE			16
#define FIELD_HSIZE			8
#define SPRITE_SIZE			26
#define HEADER_HEIGHT		32
#define SPRITE_TOPPAD		3
#define DIGIT_TOPPAD		4
#define HEADER_SIDEPAD		5
#define BORDER_SIZE			10
#define FIELD_TOPPAD		(BORDER_SIZE*2+HEADER_HEIGHT)
#define COLOR_BODY			0x00c0c0c0
#define COLOR_DARK			0x00808080
#define COLOR_BRIGHT		0x00ffffff
#define SHADE_SIZE			2
#define SHADE_INNER			0
#define SHADE_OUTER			SHADE_SIZE

#define SPRITE_NORMAL		0
#define SPRITE_PRESSED		1
#define SPRITE_REVEAL		2
#define SPRITE_LOSE			3
#define SPRITE_WIN			4
#define CLK_RELEASED		0
#define CLK_RESTART			1
#define CLK_REVEAL			2
#define CLK_PRECHORD		3
#define CLK_CHORD			4
#define CLK_WIN				8
#define CLK_LOSE			16

#define WIDTH_MIN			9
#define HEIGHT_MIN			6
#define WIDTH_MAX			96
#define HEIGHT_MAX			64
#define FIELD_MAX			(WIDTH_MAX*HEIGHT_MAX)
#define GLOBAL_WIDTH		(BORDER_SIZE*2+WIDTH_MAX*FIELD_SIZE)
#define GLOBAL_HEIGHT		(BORDER_SIZE*3+HEADER_HEIGHT+HEIGHT_MAX*FIELD_SIZE)

#define MAIN_MENU			100
#define ID_PRESET			110
#define ID_BEGINNER			110
#define ID_INTERMEDIATE		111
#define ID_EXPERT			112
#define ID_MULTI			120
#define ID_SINGLE			121
#define ID_DOUBLE			122
#define ID_TRIPLE			123
#define ID_QUADRUPLE		124
#define ID_QUINTUPLE		125
#define ID_SEXUPLE			126
#define ID_SEPTUPLE			127
#define ID_CUSTOM			150
#define ID_RESTART			170
#define ID_BESTTIME			180
#define ID_EXIT				199

#define MAIN_TIMER			200
#define HOT_RESTART			210
#define HOT_CUSTOM			220
#define HOT_BESTTIME		230
#define DLG_HELP			240
#define DLG_BESTTIME		250
#define BEST_TIME			260
#define BEST_BTIME			260
#define BEST_ITIME			261
#define BEST_ETIME			262
#define DLG_CUSTOM			300
#define CUSTOM_MULTI		310
#define CUSTOM_WIDTH		320
#define CUSTOM_HEIGHT		330
#define CUSTOM_MINE			350

#define BM_SPRITE			400
#define BM_DIGIT			410
#define BM_NUMBER			420
#define BM_MINE				430

#define FLAG				8
#define	GETSTATE(s)			(s>>3)
#define GETFLAG(s)			((s>>3)&7)
#define CLEARFLAG(s)		(s&=7)
#define GETMINE(s)			(s&7)
#define SETREVEALED(s)		(s|=64)
#define SETTRIGGERED(s)		(s|=128)
#define SETFLAG(s,f)		(s=((s&0xc7)|(f<<3)))
#define ISFLAGGED(s)		(s>=8)
#define ISREVEALED(s)		(s>=64)
#define ISUNREVEALED(s)		(s<64)
#define ISTRIGGERED(s)		(s>=128)
#define WARP(w,l)			((w+l)%l)

#define TYPE_CUSTOM			-1
#define TYPE_BEGINNER		0
#define TYPE_INTERMEDIATE	1
#define TYPE_EXPERT			2
#define TYPE_MULTI			3
#define TYPE_COUNT			21
#define TYPE_DEFAULT		TYPE_EXPERT
